<Type Name="AsynchronousOperationException" FullName="System.IdentityModel.AsynchronousOperationException">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="0557086981880cebb05d286f3f156744916cb525" />
    <Meta Name="ms.sourcegitcommit" Value="9e06b87bcfa4347dbbaaa4b3cc36b43b93b5badb" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="es-ES" />
    <Meta Name="ms.lasthandoff" Value="11/20/2018" />
    <Meta Name="ms.locfileid" Value="52245830" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class AsynchronousOperationException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AsynchronousOperationException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:System.IdentityModel.AsynchronousOperationException" />
  <TypeSignature Language="VB.NET" Value="Public Class AsynchronousOperationException&#xA;Inherits Exception" />
  <TypeSignature Language="C++ CLI" Value="public ref class AsynchronousOperationException : Exception" />
  <TypeSignature Language="F#" Value="type AsynchronousOperationException = class&#xA;    inherit Exception" />
  <AssemblyInfo>
    <AssemblyName>System.IdentityModel</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute FrameworkAlternate="netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8">
      <AttributeName>Serializable</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="1afb5-101">Excepción que se produce cuando se produce un error durante una operación asincrónica.</span>
      <span class="sxs-lookup">
        <span data-stu-id="1afb5-101">The exception that is thrown when an error occurs during an asynchronous operation.</span>
      </span>
    </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="1afb5-102">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-102">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="1afb5-103">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-103">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="1afb5-104">Este constructor inicializa la propiedad <xref:System.Exception.Message> de una nueva instancia en un mensaje proporcionado por el sistema que describe el error.</span><span class="sxs-lookup"><span data-stu-id="1afb5-104">This constructor initializes the <xref:System.Exception.Message> property of the new instance to a system-supplied message that describes the error.</span></span> <span data-ttu-id="1afb5-105">Este mensaje tiene en cuenta la referencia cultural del sistema actual.</span><span class="sxs-lookup"><span data-stu-id="1afb5-105">This message takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="1afb5-106">En la tabla siguiente muestra los valores de propiedad iniciales para la nueva instancia.</span><span class="sxs-lookup"><span data-stu-id="1afb5-106">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="1afb5-107">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="1afb5-107">Property</span></span>|<span data-ttu-id="1afb5-108">Valor</span><span class="sxs-lookup"><span data-stu-id="1afb5-108">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="1afb5-109">`null`.</span><span class="sxs-lookup"><span data-stu-id="1afb5-109">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="1afb5-110">La cadena del mensaje de error localizado.</span><span class="sxs-lookup"><span data-stu-id="1afb5-110">The localized error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException innerException" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="innerException">
          <span data-ttu-id="1afb5-111">Clase <see cref="T:System.Exception" /> que es la causa de la excepción actual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-111">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="1afb5-112">Si el parámetro <paramref name="innerException" /> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-112">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="1afb5-113">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con un mensaje de error proporcionado por el sistema y una referencia a la excepción interna que representa la causa de esta excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-113">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a system-supplied error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="1afb5-114">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="1afb5-114">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="1afb5-115">El <xref:System.Exception.InnerException%2A> propiedad devuelve el mismo valor que se pasó al constructor.</span><span class="sxs-lookup"><span data-stu-id="1afb5-115">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="1afb5-116">En la tabla siguiente muestra los valores de propiedad iniciales para la nueva instancia.</span><span class="sxs-lookup"><span data-stu-id="1afb5-116">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="1afb5-117">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="1afb5-117">Property</span></span>|<span data-ttu-id="1afb5-118">Valor</span><span class="sxs-lookup"><span data-stu-id="1afb5-118">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="1afb5-119">Referencia a la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="1afb5-119">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="1afb5-120">Un mensaje proporcionado por el sistema que describe el error.</span><span class="sxs-lookup"><span data-stu-id="1afb5-120">A system-supplied message that describes the error.</span></span> <span data-ttu-id="1afb5-121">Este mensaje tiene en cuenta la referencia cultural del sistema actual.</span><span class="sxs-lookup"><span data-stu-id="1afb5-121">This message takes into account the current system culture.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException message" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="1afb5-122">Mensaje de error que explica el motivo de la excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-122">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="1afb5-123">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con el mensaje de error especificado.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-123">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="1afb5-124">Este constructor inicializa la <xref:System.Exception.Message%2A> propiedad de la nueva excepción utilizando el `message` parámetro.</span><span class="sxs-lookup"><span data-stu-id="1afb5-124">This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter.</span></span> <span data-ttu-id="1afb5-125">Se pretende que el contenido de `message` sea inteligible.</span><span class="sxs-lookup"><span data-stu-id="1afb5-125">The content of `message` is intended to be understood by humans.</span></span> <span data-ttu-id="1afb5-126">El autor de llamada de este constructor debe asegurarse de que la cadena se haya adaptado para la referencia cultural actual del sistema.</span><span class="sxs-lookup"><span data-stu-id="1afb5-126">The caller of this constructor is required to ensure that this string has been localized for the current system culture.</span></span>  
  
 <span data-ttu-id="1afb5-127">En la tabla siguiente muestra los valores de propiedad iniciales para la nueva instancia.</span><span class="sxs-lookup"><span data-stu-id="1afb5-127">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="1afb5-128">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="1afb5-128">Property</span></span>|<span data-ttu-id="1afb5-129">Valor</span><span class="sxs-lookup"><span data-stu-id="1afb5-129">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="1afb5-130">`null`.</span><span class="sxs-lookup"><span data-stu-id="1afb5-130">`null`.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="1afb5-131">Cadena con el mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="1afb5-131">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; AsynchronousOperationException(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : System.Runtime.Serialization.SerializationInfo * System.Runtime.Serialization.StreamingContext -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (info, context)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="1afb5-132">Objeto <see cref="T:System.Runtime.Serialization.SerializationInfo" /> que contiene los datos del objeto serializados.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-132">A <see cref="T:System.Runtime.Serialization.SerializationInfo" /> object that holds the serialized object data.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="1afb5-133">Objeto <see cref="T:System.Runtime.Serialization.StreamingContext" /> que contiene la información contextual sobre el origen o el destino.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-133">A <see cref="T:System.Runtime.Serialization.StreamingContext" /> object that contains the contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="1afb5-134">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con datos serializados.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-134">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="1afb5-135">Durante la deserialización se llama a este constructor para reconstituir el objeto de excepción transmitido en una secuencia.</span><span class="sxs-lookup"><span data-stu-id="1afb5-135">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AsynchronousOperationException (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.IdentityModel.AsynchronousOperationException.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; AsynchronousOperationException(System::String ^ message, Exception ^ innerException);" />
      <MemberSignature Language="F#" Value="new System.IdentityModel.AsynchronousOperationException : string * Exception -&gt; System.IdentityModel.AsynchronousOperationException" Usage="new System.IdentityModel.AsynchronousOperationException (message, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.IdentityModel</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="1afb5-136">Mensaje de error que explica el motivo de la excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-136">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="1afb5-137">Clase <see cref="T:System.Exception" /> que es la causa de la excepción actual.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-137">The <see cref="T:System.Exception" /> that is the cause of the current exception.</span>
          </span>
          <span data-ttu-id="1afb5-138">Si el parámetro <paramref name="innerException" /> no es <see langword="null" />, la excepción actual se produce en un bloque <see langword="catch" /> que controla la excepción interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-138">If the <paramref name="innerException" /> parameter is not <see langword="null" />, the current exception is raised in a <see langword="catch" /> block that handles the inner exception.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="1afb5-139">Inicializa una nueva instancia de la clase <see cref="T:System.IdentityModel.AsynchronousOperationException" /> con el mensaje de error especificado y una referencia a la excepción interna que representa la causa de esta excepción.</span>
          <span class="sxs-lookup">
            <span data-stu-id="1afb5-139">Initializes a new instance of the <see cref="T:System.IdentityModel.AsynchronousOperationException" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="1afb5-140">Una excepción que se produce como consecuencia directa de una excepción anterior debe incluir una referencia a esta última en la propiedad <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="1afb5-140">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="1afb5-141">El <xref:System.Exception.InnerException%2A> propiedad devuelve el mismo valor que se pasó al constructor.</span><span class="sxs-lookup"><span data-stu-id="1afb5-141">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.</span></span>  
  
 <span data-ttu-id="1afb5-142">En la tabla siguiente muestra los valores de propiedad iniciales para la nueva instancia.</span><span class="sxs-lookup"><span data-stu-id="1afb5-142">The following table shows the initial property values for the new instance.</span></span>  
  
|<span data-ttu-id="1afb5-143">Propiedad.</span><span class="sxs-lookup"><span data-stu-id="1afb5-143">Property</span></span>|<span data-ttu-id="1afb5-144">Valor</span><span class="sxs-lookup"><span data-stu-id="1afb5-144">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="1afb5-145">Referencia a la excepción interna.</span><span class="sxs-lookup"><span data-stu-id="1afb5-145">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="1afb5-146">Cadena con el mensaje de error.</span><span class="sxs-lookup"><span data-stu-id="1afb5-146">The error message string.</span></span>|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>